### ISSUE TITLE
wps邀请不了人了

### ISSUE THREAD

**Issue by 1325266720** [datugou/WPS_daily_check_in#1]
求大佬更新，现在已经邀请不到人了

**Comment by RoseannePark1** [comment]
我今天也只有两天了😂

**Comment by datugou** [comment]
我这里没问题啊，是不是2个月没动过项目，Action自动停了啊，重新开启一下Action，或者随便保存修改一下

**Comment by datugou** [comment]
修复了，重新 fork 下该项目（接收邀请有时候需要等待，重新发送请求即可）
