### ISSUE TITLE
今天失效了！！！！！！

### ISSUE THREAD

**Issue by RouJiANG-14** [datugou/WPS_daily_check_in#21]
🌝🌝🌝今天失效了

**Comment by RoseannePark1** [comment]
我也是😂

**Comment by supertiny99** [comment]
是的，今天运行不起来了

**Comment by supertiny99** [comment]
手动发起了一下 POST 可以，应该是 github actions 的某些机制导致错误了

**Comment by chuyua** [comment]
我今天也是

**Comment by 1076764805** [comment]
错误，运行失败，Process completed with exit code 1
但是任务完成了，有邀请到人

**Comment by supertiny99** [comment]
![image](https://user-images.githubusercontent.com/15050148/115100521-ca59c880-9f6f-11eb-9e9d-692984a39ab3.png)
返回数据增加了个 b。。

**Comment by supertiny99** [comment]
应该是第一个 sid 可以邀请到，第二个就不行了

**Comment by supertiny99** [comment]
应该是 wps 限制了邀请人数最大数，导致第 11 次邀请报错了。
把 sid 删到 10 条就可以了。

**Comment by WangXiaoXin1998** [comment]
应该是某个sid封号了或者有其它情况导致请求出问题了，把WPS_accept_invitation.py第35行改为：
`        try:`
`            r = request_re(j, i)`
`            js = json.loads(r.content)`
`            if js['result'] == 'ok':`
`                mk += 1`
`        except:`
`            print('发生未知错误')`
一劳永逸

**Comment by cyczq11** [comment]
我也是

**Comment by RouJiANG-14** [comment]
> 应该是某个sid封号了或者有其它情况导致请求出问题了，把WPS_accept_invitation.py第35行改为：
> ` try:`
> ` r = request_re(j, i)`
> ` js = json.loads(r.content)`
> ` if js['result'] == 'ok':`
> ` mk += 1`
> ` except:`
> ` print('发生未知错误')`
> 一劳永逸

代码基础差，自己尝试了一下发现不行，36行报错。
只能删除多余的sid，10个sid的时候就提示成功了。

**Comment by WangXiaoXin1998** [comment]
> > 应该是某个sid封号了或者有其它情况导致请求出问题了，把WPS_accept_invitation.py第35行改为：
> > ` try:`
> > ` r = request_re(j, i)`
> > ` js = json.loads(r.content)`
> > ` if js['result'] == 'ok':`
> > ` mk += 1`
> > ` except:`
> > ` print('发生未知错误')`
> > 一劳永逸
> 
> 代码基础差，自己尝试了一下发现不行，36行报错。
> 只能删除多余的sid，10个sid的时候就提示成功了。

报错的话检查下是不是没有缩进对。原理就是加个try...catch。删除成功我怀疑是你和楼上的正好删到了（可能）被封号的那个sid。我刚开始删了前2个还是报错。

**Comment by supertiny99** [comment]
```
try:
    r = request_re(j, i)
    js = json.loads(r.content)
    if js['result'] == 'ok':
          mk += 1
except:
    print('发生未知错误')
```

**Comment by datugou** [comment]
经验证，发现最后一条sid发送请求时会报错，已修复。感谢大家提供意见
