### ISSUE TITLE
无论怎么改都邀请不到10个人，最多是9个。

### ISSUE THREAD

**Issue by RouJiANG-14** [datugou/WPS_daily_check_in#3]
重复次数改到了50，间隔改到了4也不行。
怀疑是不是上面的wps_sid失效了？我自行添加的不知道怎么回事，添加后就无法运行了。

**Comment by datugou** [comment]
应该是有人用别的wps_sid账号接收过你那俩个wps ID的邀请，所以这个项目里的wps_sid只有9个能接受。
你在手机上微信小程序查看下任务，应该是已经邀请了10位好友了。

**Comment by datugou** [comment]
![image](https://user-images.githubusercontent.com/30107520/108954691-27d84400-76a8-11eb-9fad-350b8382399b.png)

**Comment by RouJiANG-14** [comment]
谢谢，设置的4  0 * * * 今天8点04没运行我寻思是不是设置成昨天了？？哈哈 改成 30 23 * * *明天再看看七点半运行不。。

**Comment by datugou** [comment]
每天到点都会运行，不分今天还是昨天。运行的时间会比设置的时间晚一些，像我设置的上午 9 点，今天实际运行时间是 9：30 多。
