### ISSUE TITLE
怎么修改运行时间？

### ISSUE THREAD

**Issue by z279493** [datugou/WPS_daily_check_in#35]
大佬，怎么修改运行时间？在那个代码修改啊？

**Comment by datugou** [comment]
在文件夹 .github/workflows/wps_dci.yml 修改，

# 第 8 行代码
- cron: '0 1 * * *'
# 第一个数表示分钟（范围 0 - 59）
# 第二个数表示国际标准时间 1 点（北京时间上午 9 点）（范围 0 - 23）
# 改动前两个二个数即可，不要动后面的三个 *

实际运行时间比设置晚半小时左右
