### ISSUE TITLE
找10个号还是可以的，

### ISSUE THREAD

**Issue by daqueque** [datugou/WPS_daily_check_in#54]
测试找10个号还是可以的

**Comment by chennanab** [comment]
> 测试找10个号还是可以的

有便捷的提取invite_sid的方法么？

**Comment by daqueque** [comment]
> > 测试找10个号还是可以的
> 
> 有便捷的提取invite_sid的方法么？

**Comment by daqueque** [comment]
> > 测试找10个号还是可以的
> 
> 有便捷的提取invite_sid的方法么？

需要用sid登录，可以登录http://zt.wps.cn，查看cookie里的sid获取

**Comment by chennanab** [comment]
> > > 测试找10个号还是可以的
> > 
> > 
> > 有便捷的提取invite_sid的方法么？
> 
> 需要用sid登录，可以登录[http://zt.wps.cn，查看cookie里的sid获取](http://zt.wps.cn%EF%BC%8C%E6%9F%A5%E7%9C%8Bcookie%E9%87%8C%E7%9A%84sid%E8%8E%B7%E5%8F%96)

我用浏览器微信扫码登陆，看cookies里面只有wps_sid，那个和invite_sid好像有点不一样。sid登陆是怎么登陆，用会员号么？

**Comment by chennanab** [comment]
> 测试找10个号还是可以的

刚才微信小程序又更新了，现在每次进去的sid都不一样了，给你说一下哈！

**Comment by daqueque** [comment]
> > 测试找10个号还是可以的
> 
> 刚才微信小程序又更新了，现在每次进去的sid都不一样了，给你说一下哈！

我吐了...
