### ISSUE TITLE
和新版Server酱的适配

### ISSUE THREAD

**Issue by RouJiANG-14** [datugou/WPS_daily_check_in#8]
我有模有样的按照老版的配置加了一条SERVER2_KEY在Secrets 中，
WPS_accept_invitation.py的代码中也添加了差不多的代码
`SERVER2_KEY = os.getenv('SERVER2_KEY')`
`if SERVER2_KEY:`
    `data = {`
        `'text':'WPS邀请好友任务：成功邀请到%d位好友'%(mk),`
        `'desp':'3个帐号成功邀请%d位好友\n记得签到打卡哟！\n--------------------\n↓↓↓↓签到页面↓↓↓↓：\nhttps://mp.weixin.qq.com/s/ESoEklsxxBF4fA9N3Pm6eQ'%(mk)`
    `}`
    `requests.post('https://sctapi.ftqq.com/%s.send'%(SERVER2_KEY.strip()), data = data)`
但是运行下来旧版Server酱的提示正常，新版的没有动静，运行也没有报错。
不知道是哪里的问题....是requests.post的问题么？应该怎么改？
麻烦大佬了！

**Comment by datugou** [comment]
新版SERVER酱，微信登陆后需要去[消息通道](https://sct.ftqq.com/forward)设置，选择‘方糖服务号’并保存，然后才可以正常从方糖公众号收到消息。（也可以选择其它收消息渠道，每种都需要按各自的方式进行配置）

**Comment by RouJiANG-14** [comment]
> 新版SERVER酱，微信登陆后需要去[消息通道](https://sct.ftqq.com/forward)设置，选择‘方糖服务号’并保存，然后才可以正常从方糖公众号收到消息。（也可以选择其它收消息渠道，每种都需要按各自的方式进行配置）

提示即将弃用，不要选择。哭笑不得。
我以为企业微信号的推送就按照文件里的代码，依葫芦画瓢的改一个就行呢。
看来是我太天真。看了下调用方法，就是更改接口地址和新的SendKey就行啊。
不知道哪里出问题。

**Comment by datugou** [comment]
好像要自己注册一个企业号才行，我也没用过
